In [112]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

In [113]:
warnings.filterwarnings('ignore')

In [114]:
df = pd.read_csv("Travel.csv")

In [115]:
print(df.duplicated().sum(),"\n")
print(df.isna().sum())

0

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [116]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [117]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [118]:
df['Gender'].replace('Fe Male', 'Female', inplace=True)

In [119]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [120]:
df['MaritalStatus'].replace('Unmarried', 'Single', inplace=True)

In [121]:
features_with_na = [features for features in df.columns if df[features].isnull().sum() > 1]
for feature in features_with_na:
    print(f"{feature} has {np.round(df[feature].isnull().mean()*100, 5)}% missing values")

Age has 4.62357% missing values
TypeofContact has 0.51146% missing values
DurationOfPitch has 5.13502% missing values
NumberOfFollowups has 0.92062% missing values
PreferredPropertyStar has 0.53191% missing values
NumberOfTrips has 2.86416% missing values
NumberOfChildrenVisiting has 1.35025% missing values
MonthlyIncome has 4.76678% missing values

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [123]:
for col in df.columns: 
    if df[col].dtype in ['int64', 'float64']:
        df[col].fillna(df[col].median(), inplace=True)
        
    elif df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)

In [124]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [125]:
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df.drop(columns=['CustomerID', 'NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis=0, inplace=True)

df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [126]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

X = df.drop(columns=['ProdTaken'], axis=1)
y = df['ProdTaken']

cat_features =  [one for one in X.columns if X[one].dtype == 'O']
num_features =  [one for one in X.columns if X[one].dtype != 'O']

oh_encoder = OneHotEncoder(drop='first')
sclaer = StandardScaler()

preprocess = ColumnTransformer(
    [
        ("OneHotEncoder", oh_encoder, cat_features),
        ("StandardScaler", sclaer, num_features)
    ]
)

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

X_train = preprocess.fit_transform(X_train)
X_test = preprocess.transform(X_test)

In [129]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Gaussian Navie Bayes": GaussianNB(),
    "Support Vector Machines": SVC(),
    "RandomForest": RandomForestClassifier()
    }

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')
    model_train_precision = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train, y_train_pred)
    
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')
    model_test_precision = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred)

    print("-------", list(models.keys())[i], "-------")
    print("\n")          

    print('Model Performance for Training Set')
    print("- Accuracy: {:.4f}".format(model_train_accuracy))            
    print("- F1 Score: {:.4f}".format(model_train_f1))            
    print("- Precision: {:.4f}".format(model_train_precision))            
    print("- Recall: {:.4f}".format(model_train_recall))            
    print("- roc auc score: {:.4f}".format(model_train_rocauc_score))            
    print("\n")          

    print('Model Performance for Test Set')
    print("- Accuracy: {:.4f}".format(model_test_accuracy))            
    print("- F1 Score: {:.4f}".format(model_test_f1))            
    print("- Precision: {:.4f}".format(model_test_precision))            
    print("- Recall: {:.4f}".format(model_test_recall))            
    print("- roc auc score: {:.4f}".format(model_test_rocauc_score))  
    print("="*35)
    print("\n")

------- Logistic Regression -------


Model Performance for Training Set
- Accuracy: 0.8473
- F1 Score: 0.8218
- Precision: 0.7328
- Recall: 0.3163
- roc auc score: 0.6445


Model Performance for Test Set
- Accuracy: 0.8428
- F1 Score: 0.8210
- Precision: 0.6392
- Recall: 0.3227
- roc auc score: 0.6410
===================================


------- Decision Tree -------


Model Performance for Training Set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- roc auc score: 1.0000


Model Performance for Test Set
- Accuracy: 0.8854
- F1 Score: 0.8854
- Precision: 0.6869
- Recall: 0.6869
- roc auc score: 0.8084
===================================


------- Gaussian Navie Bayes -------


Model Performance for Training Set
- Accuracy: 0.6997
- F1 Score: 0.7288
- Precision: 0.3516
- Recall: 0.6771
- roc auc score: 0.6911


Model Performance for Test Set
- Accuracy: 0.6967
- F1 Score: 0.7279
- Precision: 0.3344
- Recall: 0.6645
- roc auc score: 0.6842
===================================


------- Support Vector Machines -------


Model Performance for Training Set
- Accuracy: 0.8933
- F1 Score: 0.8797
- Precision: 0.9161
- Recall: 0.4860
- roc auc score: 0.7377


Model Performance for Test Set
- Accuracy: 0.8714
- F1 Score: 0.8518
- Precision: 0.8163
- Recall: 0.3834
- roc auc score: 0.6820
===================================


------- RandomForest -------


Model Performance for Training Set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- roc auc score: 1.0000


Model Performance for Test Set
- Accuracy: 0.9117
- F1 Score: 0.9043
- Precision: 0.8932
- Recall: 0.5879
- roc auc score: 0.7861
===================================